[project]
name = "xrd-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "h5py>=3.14.0",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "pyyaml>=6.0.2",
]
